# Generated by Django 4.2.13 on 2024-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
