# Generated by Django 4.2.13 on 2024-07-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_pin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_unit_no',
        ),
    ]
