# Generated by Django 4.2.13 on 2024-07-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_checkout_billing_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
