# Generated by Django 5.0.6 on 2024-06-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_order_date_order_ordered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_unit_no', models.CharField(max_length=100)),
                ('shipping_street', models.CharField(max_length=200)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_pin', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('billing_unit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=4)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.checkout')),
            ],
        ),
    ]
