# Generated by Django 4.2.13 on 2024-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='Reward points for the product'),
        ),
    ]
