# Generated by Django 4.2.13 on 2024-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_userregistration_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reward_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
