# Generated by Django 4.2.13 on 2024-06-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password2',
        ),
    ]
