# Generated by Django 4.2.13 on 2024-07-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_reward_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reward_points',
        ),
    ]
