# Generated by Django 4.2.13 on 2024-07-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
