# Generated by Django 4.2.13 on 2024-07-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_checkout_carddetails'),
        ('marketplace', '0004_rename_password1_userregistration_password_and_more'),
    ]

    operations = [
    ]
