# Generated by Django 4.2.13 on 2024-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_product_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='reward_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
