# Generated by Django 4.2.13 on 2024-07-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='computed_reward_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
