# Generated by Django 4.2.13 on 2024-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_merge_20240701_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255),
        ),
    ]
