# Generated by Django 5.0.6 on 2024-07-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_merge_20240701_1743'),
        ('marketplace', '0005_merge_20240701_1911'),
    ]

    operations = [
    ]
