# Generated by Django 5.0.6 on 2024-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_merge_20240701_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='cardholder_name',
            new_name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='billing_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='billing_pin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='billing_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='billing_unit_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_unit_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255),
        ),
    ]
