# Generated by Django 5.0.6 on 2024-07-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_merge_20240707_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_required', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_pin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_unit_no',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_unit_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=255),
        ),
    ]
