# Generated by Django 4.2.13 on 2024-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_cartitem_computed_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='computed_reward_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
