# Generated by Django 4.2.13 on 2024-07-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_userregistration_profile_picture_and_more'),
        ('marketplace', '0007_reward_remove_carddetails_checkout_and_more'),
    ]

    operations = [
    ]
