# Generated by Django 5.0.6 on 2024-07-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_pin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_unit_no',
        ),
    ]
