# Generated by Django 4.2.13 on 2024-07-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_merge_20240709_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.checkout'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='billing_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='billing_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='billing_unit_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_unit_no',
            field=models.CharField(max_length=100),
        ),
    ]
