# Generated by Django 4.2.13 on 2024-07-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_cartitem_is_favorite_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='security_answer1',
            field=models.CharField(default='Default Question', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='security_answer2',
            field=models.CharField(default='Default Answer', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='security_question1',
            field=models.CharField(default='Default Question', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='security_question2',
            field=models.CharField(default='Default Answer', max_length=255),
            preserve_default=False,
        ),
    ]
