# Generated by Django 4.2.13 on 2024-07-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0011_userregistration_security_answer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='marketplace.product'),
        ),
    ]
