# Generated by Django 5.0.7 on 2024-07-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_product_quantity'),
        ('marketplace', '0012_remove_userregistration_email_and_more'),
    ]

    operations = [
    ]
