# Generated by Django 5.0.6 on 2024-07-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_cart_created_at_order_product_name_product_quantity_and_more'),
        ('marketplace', '0013_merge_20240712_2050'),
    ]

    operations = [
    ]
