# Generated by Django 4.2.13 on 2024-07-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbon_emission',
            field=models.PositiveIntegerField(help_text='Carbon emission reduction percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category'),
        ),
    ]
