# Generated by Django 4.2.13 on 2024-07-14 15:58

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_product_carbon_emission_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=marketplace.models.get_upload_path),
        ),
    ]
