# Generated by Django 4.2.13 on 2024-07-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_merge_20240712_2050'),
        ('marketplace', '0016_alter_product_image'),
    ]

    operations = [
    ]
