# Generated by Django 4.2.13 on 2024-07-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_cart_created_at_order_product_name_product_quantity_and_more'),
        ('marketplace', '0017_merge_20240715_0052'),
    ]

    operations = [
    ]
