# Generated by Django 5.0.7 on 2024-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_merge_20240715_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
