# Generated by Django 5.0.7 on 2024-07-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_merge_20240715_1234'),
        ('marketplace', '0018_merge_20240715_1226'),
    ]

    operations = [
    ]
