# Generated by Django 5.0.7 on 2024-07-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_merge_20240715_1234'),
        ('marketplace', '0019_remove_order_total_price_userregistration_last_visit_and_more'),
    ]

    operations = [
    ]
