# Generated by Django 5.0.7 on 2024-07-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_merge_20240715_1356'),
        ('marketplace', '0020_remove_order_total_price_userregistration_last_visit_and_more'),
    ]

    operations = [
    ]
