# Generated by Django 5.0.7 on 2024-07-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_merge_20240716_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
